version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: musicdb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: musicdb
      MYSQL_USER: musicuser
      MYSQL_PASSWORD: musicpass
    volumes:
      - ./backend/database/scripts/create_tables.sql:/docker-entrypoint-initdb.d/init.sql
